#!/bin/bash

if [[ "$1" == "-?" ]] || [[ "$1" == "--help" ]] || [[ $# -gt 1 ]] ; then
    exec "@@JAVAEXECUTABLE@@" -jar "@@INSTALLDIR@@/arx-@@VERSION@@-cli.jar" $*
    exit 0
fi

exec "@@INSTALLDIR@@/arx-launcher.run"

